import StyledComponentsRegistry from "@/lib/antd.registry";
import type { Metadata } from "next"; // For typing metadata in Next.js
import { Inter } from "next/font/google"; // Import Google font helper

// Load Inter font with Latin subset
const inter = Inter({ subsets: ["latin"] });

// Export static metadata for SEO
export const metadata: Metadata = {
  title: "Create Next App", // Page title
  description: "Generated by create next app", // Meta description
};

// Root layout component for the entire app
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap children with registry to enable AntD or styled-components SSR */}
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
